### ISSUE TITLE
請問一些設定的問題

### ISSUE THREAD

**Issue by changchichung** [andy0130tw/iridium-bpmf#2]
請問以下這兩點，是在哪個yaml 裏面設定？ 我好像都找不到..

模擬新注音的行為，可以直接用「注音+空格」輸入注音本身、「聲調」鍵直接輸入聲調
 Backspace 退格時，已完成組字的字會整字刪除，而非逐音節刪除

**Comment by andy0130tw** [comment]
配置完成就會有了，不需要額外設定
